### ISSUE TITLE
issues with cube exercise

### ISSUE THREAD

**Issue by stone147** [uclid/CGProj#4]
this is the error I get when I run your code on jsbin

"error"
"ReferenceError: THREE is not defined
    at <anonymous>:19:17
    at https://static.jsbin.com/js/prod/runner-4.1.4.min.js:1:13924
    at https://static.jsbin.com/js/prod/runner-4.1.4.min.js:1:10866

**Comment by uclid** [comment]
Three.js is a dependency for this exercise. Please make sure you have included the library properly.
